//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Type_Vehicle
    {
        public int Id { get; set; }
        public string Police_Number { get; set; }
        public Nullable<int> Stnk_Number { get; set; }
        public Nullable<int> Machine_Number { get; set; }
        public Nullable<int> Bpkb_Number { get; set; }
        public string Bpkb_Owner { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Order_Number { get; set; }
        public int Type_Vehicle_Id { get; set; }
    
        public virtual Type_Vehicle Type_Vehicle { get; set; }
    }
}
