//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Business
    {
        public int Id { get; set; }
        public Nullable<int> Business_Age { get; set; }
        public string Street { get; set; }
        public int Business_Financing_Id { get; set; }
        public string Village_Id { get; set; }
    
        public virtual Village Village { get; set; }
        public virtual Type_Business_Financing Type_Business_Financing { get; set; }
    }
}
