//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gold_Saving
    {
        public int Id { get; set; }
        public Nullable<long> Account_Number { get; set; }
        public string Type { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Transaction_Id { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
