//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_Vehicle()
        {
            this.Detail_Type_Vehicle = new HashSet<Detail_Type_Vehicle>();
        }
    
        public int Id { get; set; }
        public string Vehicle_Type { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public Nullable<int> Cylinder { get; set; }
        public Nullable<int> Years_Of_Buy { get; set; }
        public Nullable<decimal> Market_Price { get; set; }
        public string Condition { get; set; }
        public int Transaction_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Type_Vehicle> Detail_Type_Vehicle { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
