//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Business_Financing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_Business_Financing()
        {
            this.Detail_Business = new HashSet<Detail_Business>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Capital_Requirement { get; set; }
        public string Business_Type { get; set; }
        public Nullable<decimal> Turnover { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public int Transaction_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Business> Detail_Business { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
