//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPegadaian.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebPegadaianEntities : DbContext
    {
        public WebPegadaianEntities()
            : base("name=WebPegadaianEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail_Business> Detail_Business { get; set; }
        public virtual DbSet<Detail_Type_Vehicle> Detail_Type_Vehicle { get; set; }
        public virtual DbSet<Electronic> Electronics { get; set; }
        public virtual DbSet<Gold> Golds { get; set; }
        public virtual DbSet<Gold_Saving> Gold_Saving { get; set; }
        public virtual DbSet<Handphone> Handphones { get; set; }
        public virtual DbSet<Installment> Installments { get; set; }
        public virtual DbSet<Installment_type> Installment_type { get; set; }
        public virtual DbSet<Jewelry> Jewelries { get; set; }
        public virtual DbSet<Outlet> Outlets { get; set; }
        public virtual DbSet<Precious_Metal> Precious_Metal { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Type_Business_Financing> Type_Business_Financing { get; set; }
        public virtual DbSet<Type_Laptop> Type_Laptop { get; set; }
        public virtual DbSet<Type_Vehicle> Type_Vehicle { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Regency> Regencies { get; set; }
    }
}
